#!/bin/bash	
if [ "$EUID" -ne 0 ]
  then echo "Please run as root or with sudo"
  exit
fi
# Uninstall script 
. /usr/local/lib/deskpi-log-functions

# Stop deskpi.service.
systemctl stop deskpi.service
systemctl disable deskpi.service

# Define file locations
installation_dir="/home/pi/deskpi"
# Greetings and information for user.
echo "Welcome to Use DeskPi-Team's Product"
echo "Please select what distribution you have: "
echo "1 - Raspbian"
echo "2 - Manjaro/Arch"
echo "3 - Ubuntu Mate"
echo "4 - Kali"
echo "5 - Fedora"
echo "6 - Cancel Uninstallation Process"
echo "Just input the number and press enter."
read -p "Your choice:" os_type
case $os_type in
	1) 
	   echo "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	2) 
	   echo "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-manjaro.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	3) 
	   echo "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-ubuntu-mate.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	4) 
	   echo "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-kali.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	5) 
	   echo "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-fedora.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	6) 
	   echo "Uninstallation Canceled"
	   ;;
	*) 
	   echo "Error selection please try again"
	   . /usr/local/bin/Deskpi-uninstall
	   ;;
esac
